mysql -uroot -p$MYSQL_ROOT_PASSWORD <<EOSQL
GRANT ALL ON *.* TO root@'10.5.0.%' IDENTIFIED BY 'root';
CHANGE MASTER TO MASTER_HOST='10.5.0.10', MASTER_USER='repl', MASTER_PASSWORD='repl', MASTER_CONNECT_RETRY=60;
start slave;
EOSQL
